import sys

with open('frontend/src/Draw3D.jsx', 'r', encoding='utf-8') as f:
    content = f.read()

# Fix all the malformed style objects generated by the previous bad f-string
content = content.replace(
    "style={ fontSize: '0.8rem', display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', marginTop: '0.5rem' }",
    "style={{ fontSize: '0.8rem', display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', marginTop: '0.5rem' }}"
)
content = content.replace(
    "style={ fontSize: '0.8rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }",
    "style={{ fontSize: '0.8rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}"
)
content = content.replace(
    "style={ transform: 'scale(1.2)' }",
    "style={{ transform: 'scale(1.2)' }}"
)
content = content.replace(
    "style={ width: '50px', padding: '2px', textAlign: 'right', border: '1px solid #cbd5e1', borderRadius: '4px' }",
    "style={{ width: '50px', padding: '2px', textAlign: 'right', border: '1px solid #cbd5e1', borderRadius: '4px' }}"
)

with open('frontend/src/Draw3D.jsx', 'w', encoding='utf-8') as f:
    f.write(content)

print('done')
